---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: <%= ENV['CHEF_VERSION'] || 'latest' %>

verifier:
  name: inspec

platforms:
  - name: windows-2016

suites:
  - name: default
    run_list:
      - recipe[sbp_sysinternals::default]
    verifier:
      inspec_tests:
        - test/smoke/default
